# Google OAuth credentials
# Replace these values with your actual Google OAuth credentials
[google_auth]
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8501"  # Default Streamlit port

# Add any other secrets your application needs below
