"""
Data models for Canberra Charities Database.
Defines the schema for charity records including governance, technology, and functions.
"""

# Sector categories based on ACNC charitable subtypes and ACT community service categories
SECTOR_CATEGORIES = [
    "Disability Services",
    "Mental Health",
    "Homelessness & Housing",
    "Youth Services",
    "Aged Care & Seniors",
    "Family & Domestic Violence",
    "Multicultural & Refugee Services",
    "Aboriginal & Torres Strait Islander",
    "Health & Medical",
    "Education & Training",
    "Environment & Conservation",
    "Arts & Culture",
    "Sport & Recreation",
    "Animal Welfare",
    "Emergency Relief & Food",
    "Legal & Advocacy",
    "LGBTIQ+ Services",
    "Community Development",
    "Religious & Faith-Based",
    "Employment Services",
    "Children & Early Childhood",
    "Veteran Services",
    "Addiction & Recovery",
    "Financial Counselling",
    "Peak Body / Sector Support",
    "Philanthropy & Grantmaking",
    "Other",
]

# Core organisational functions common across charities
ORGANISATIONAL_FUNCTIONS = [
    "Board Governance & Strategic Planning",
    "Executive Leadership & Management",
    "Finance & Accounting",
    "Fundraising & Development",
    "Grant Writing & Acquittal",
    "Service Delivery & Programs",
    "Case Management",
    "Client Intake & Assessment",
    "Volunteer Management",
    "Human Resources & Staffing",
    "Marketing & Communications",
    "Social Media & Digital Presence",
    "Compliance & Regulatory Reporting",
    "Quality Assurance & Accreditation",
    "Impact Measurement & Evaluation",
    "IT & Systems Administration",
    "Data Management & Privacy",
    "Advocacy & Policy",
    "Community Engagement",
    "Partnerships & Stakeholder Relations",
    "Event Management",
    "Risk Management",
    "Training & Professional Development",
    "Property & Facilities Management",
    "Transport & Logistics",
]

# Common technology systems in the Australian NFP sector
TECHNOLOGY_CATEGORIES = {
    "CRM & Donor Management": [
        "Salesforce Nonprofit Cloud",
        "Microsoft Dynamics 365",
        "Keela",
        "SupporterHub",
        "ChilliDB",
        "Community CRM",
        "Vega.Works",
        "Bloomerang",
        "Neon One",
        "Custom/Bespoke CRM",
        "No dedicated CRM",
    ],
    "Accounting & Finance": [
        "Xero",
        "MYOB",
        "QuickBooks",
        "Calxa",
        "Access Group ERP",
        "Spreadsheets only",
        "Other",
    ],
    "Case Management": [
        "Salesforce Case Management",
        "SmarterSoft",
        "Infoxchange",
        "iInsight",
        "Penelope",
        "DEX (Data Exchange)",
        "Custom/Bespoke",
        "Paper-based",
        "Not applicable",
    ],
    "Volunteer Management": [
        "Rosterfy",
        "Better Impact",
        "VolunteerHub",
        "Volunteolution",
        "Spreadsheets",
        "Not applicable",
    ],
    "Communications & Marketing": [
        "Mailchimp",
        "Campaign Monitor",
        "Constant Contact",
        "Dotdigital",
        "HubSpot",
        "Manual/None",
    ],
    "Website Platform": [
        "WordPress",
        "Wix",
        "Squarespace",
        "Drupal",
        "Custom Built",
        "No website",
    ],
    "Office Productivity": [
        "Microsoft 365",
        "Google Workspace",
        "Both",
        "Other",
    ],
    "HR & Payroll": [
        "MYOB PayGlobal",
        "Xero Payroll",
        "Employment Hero",
        "KeyPay",
        "ADP",
        "Manual/Spreadsheets",
        "All volunteer (N/A)",
    ],
}

# Charity size categories
SIZE_CATEGORIES = [
    "Micro (< $50K revenue)",
    "Small ($50K - $250K)",
    "Medium ($250K - $1M)",
    "Large ($1M - $10M)",
    "Very Large ($10M+)",
    "Unknown",
]

# Record schema as a reference
CHARITY_RECORD_FIELDS = {
    "id": "Auto-increment unique ID",
    "name": "Official charity/NFP name",
    "abn": "Australian Business Number",
    "acnc_registered": "Registered with ACNC (Yes/No/Unknown)",
    "registration_status": "Active/Revoked/Voluntarily Revoked",
    "sector_primary": "Primary sector category",
    "sector_secondary": "Secondary sector category (optional)",
    "purpose": "Mission statement / stated purpose",
    "activities": "Key activities and programs",
    "clients_served": "Who they serve (target population)",
    "geographic_focus": "Where they operate within ACT",
    "size_category": "Organisation size based on revenue",
    "annual_revenue": "Approximate annual revenue if known",
    "staff_count": "Number of paid staff (approx)",
    "volunteer_count": "Number of volunteers (approx)",
    "membership_count": "Number of members if membership-based",
    "ceo_name": "CEO / Executive Director name",
    "ceo_title": "CEO title (CEO, ED, GM, etc.)",
    "chair_name": "Board Chair / President name",
    "board_members": "Known board/committee members (JSON list)",
    "board_size": "Number of board members",
    "website": "Organisation website URL",
    "email": "General contact email",
    "phone": "Contact phone number",
    "address": "Physical address",
    "suburb": "Suburb within Canberra",
    "postcode": "Postcode",
    "facebook": "Facebook page URL",
    "linkedin": "LinkedIn page URL",
    "instagram": "Instagram handle",
    "technology_crm": "CRM system used",
    "technology_accounting": "Accounting system",
    "technology_case_mgmt": "Case management system",
    "technology_website": "Website platform",
    "technology_office": "Office productivity suite",
    "technology_other": "Other notable technology",
    "functions": "Core organisational functions (JSON list)",
    "hands_across_partner": "Partner of Hands Across Canberra (Yes/No/Unknown)",
    "grant_recipient_cfc": "Canberra Foundations Collaborative grant recipient",
    "ndis_registered": "NDIS registered provider (Yes/No/Unknown)",
    "dgr_status": "Deductible Gift Recipient status",
    "year_established": "Year organisation was established",
    "last_verified": "Date this record was last verified",
    "data_source": "Source of data (ACNC, web, manual, etc.)",
    "notes": "Additional notes",
}
